---
title: "Content page"
output: 
  html_document: 
    highlight: monochrome
    theme: united
date: "2023-03-11"
---

## R notes sorted by lecture :D {.tabset}

### Overview

1.  [Introduction to R](https://flatter11.github.io/r.studio/1.-Introduction-to-R)

2.  [Regression in R](https://flatter11.github.io/r.studio/2.-Regression-in-R) 
    -   Graph, random numbers, linear regression
    
3.  [Applied regression I](https://flatter11.github.io/r.studio/3.-Applied-regression-I)
    -   Generalized linear model, poisson regression
    
4.  [Applied regression II](https://flatter11.github.io/r.studio/4.-Applied-regression-II)
    -   Overdispersion -- negative binomial distribution, checking influential observations, model diagnostics to check assumptions violated
    
5.  [Applied regression III](https://flatter11.github.io/r.studio/5.-Applied-regression-III)
    -   Multicollinearity, confounding, effect modification, mediation
    
6.  [Conditional logistic regression and propensity score method](https://flatter11.github.io/r.studio/6.-Conditional-logistic-regression-and-propensity-score-method)
    -   clogit for matched case-control study, propensity score for confounding
    
7.  [Inverse probability weighting and meta analysisd](https://flatter11.github.io/r.studio/7.-Inverse-probability-weighting-and-meta-analysis)
    -   IPW for missing data, meta analysis (fixed/random effect model, forest, 
        funnel plot)
8.  [Instrumental variable analysis](https://flatter11.github.io/r.studio/8.-Instrumental-variable-analysis)
    -   Wald estimate, 2SLS

Tutorials
1.  [Regression in R](https://flatter11.github.io/r.studio/Tutorial-1)
    -   Use `runif` `sample` to prove central limit theorem; fit linear regression
        model
        
2.  [Applied regression](https://flatter11.github.io/r.studio/Tutorial-2)       
    [Key point](https://flatter11.github.io/r.studio/Tutorial-2_keypoints)
    -   Exploratory analysis (cross tabulation, boxplot), confounder, effect 
        modification with **subgroup analysis**, collinearity, mediation analysis,
        **model selection** with `stepAIC`, summarize results

### 1

[1. Introduction to R](https://flatter11.github.io/r.studio/1.-Introduction-to-R)

1.  Use of R as a calculator
2.  Vectors, matrices, and their operations
3.  Logic in R
4.  Data frames
5.  Summaries, tables

### 2

[2. Regression in R](https://flatter11.github.io/r.studio/2.-Regression-in-R)

1.  Graphs
2.  Generating random numbers following uniform, binomial, normal distribution
3.  **Linear regression**       
    Regression related codes:
    -   `cut` categorizing continous variable
    -   `confint` 95%CI
    -   `AIC` `StepAIC`
    -   `predict` fit new data to a model
4.  Others
    -   `shaprio` check normality for a set of data
    -   IF and FOR statement

### 3

[3. Applied regression I](https://flatter11.github.io/r.studio/3.-Applied-regression-I)

1.  What is count data and **poisson distribution**
2.  Generalized linear model
    -   goodness-of-fit for model checking
    -   `predict` for model checking
3.  Overdispersion

### 4

[4. Applied regression II](https://flatter11.github.io/r.studio/4.-Applied-regression-II)

1.  Overdispersion and **negative binomial distribution**
2.  Checking influential observations
    -   Leverage
    -   Cook’s distance
3.  Model diagnostics to check for any assumptions violated
    -   Linearity
    -   Heteroscedasticity of the errors
    -   Non-normality of the errors
    -   Non-independence of the errors

### 5

[5. Applied regression III](https://flatter11.github.io/r.studio/5.-Applied-regression-III)

1.  Multicollinearity
    -   Diagnostic: Variance inflation factor (VIF) > 10 `vif`
    -   Solution: Centering to solve multicollinearity `scale`
2.  Confounding
    -   Diagnostic
        -   Automatic variable selection (AIC) `stepAIC`
        -   Relative change in estimate greater than 10%
        -   Standard rules
3.  Effect modification
    -   Solution: Add interaction term in regression model
4.  Mediation
    -   Diagnostic
        -   Baron and Kenny criteria
        -   Sobel test `sobel`

### 6

[6. Conditional logistic regression and propensity score method](https://flatter11.github.io/r.studio/6.-Conditional-logistic-regression-and-propensity-score-method)

1.  Conditional logistic regression -- conditional analysis for individual matching `clogit`
2.  Propensity score (PS) for confounding
    -   How to derive PS
    -   PS analysis
        1.  Stratification
        2.  Matching
        3.  Adjustment

### 7

[7. Inverse probability weighting and meta analysisd](https://flatter11.github.io/r.studio/7.-Inverse-probability-weighting-and-meta-analysis)

1.  **Inverse probability weighting** for missing data
2.  **Meta analysis**
    -   Heterogeneity (fixed and random effect model)
    -   Forest plot
    -   Funnel plot

### 8

[8. Instrumental variable analysis](https://flatter11.github.io/r.studio/8.-Instrumental-variable-analysis)

1.  **Wald estimate**
2.  **2SLS**
3.  Test for weak relevance (1st assumption violation)
4.  IV vs regression

### T1

[Regression in R](https://flatter11.github.io/r.studio/Tutorial-1)

1.  Use `runif` for uniform distribution; `sample` for bimodal discrete 
    distribution to prove central limit theorem     
    `shapiro.test` to check noramlity
2.  Fit linear gression model
    -   `cut` to categorize groups
    -   `aggregate` to calculate summary statistics
    -   `boxplot`; `plot` to draw scatterplot + `abline(lm(model))` to add 
        regression line **[[very complicated question]]**
    -   Quadratic relationship
    -   `stepAIC` for model selection
    -   `predict` to predict result with model

### T2

[Applied regression](https://flatter11.github.io/r.studio/Tutorial-2)
[Applied regression](https://flatter11.github.io/r.studio/Tutorial-2_keypoints)

1.  Exploratory analysis (cross tabulation, boxplot)
2.  Confounder, effect modification with **subgroup analysis**, collinearity, 
    mediation analysis
3.  **Model selection** with `stepAIC`
4.  Summarize results
